mysite/food/urls.py
from . import views
from django.urls import path,reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

app_name = 'food'
urlpatterns = [
    path('', views.index_class_view.as_view(),name='index'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
   
    path('add/', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:pk>/', views.UpdateItem.as_view(), name='update_item'),
    path('delete/<int:pk>/', views.ItemDeleteView.as_view(), name='delete_item'),
    path('<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('detail')), name='comment_delete'),
    path('like/<int:pk>/', views.LikeView, name='like_item'),
    path('searched_item/', views.SearchView, name='searched_item'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static
from users import views
from users.views import UpdateProfile, CreateProfile


urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/",include('food.urls')),
   
    path("register/", user_views.register, name='register'),
    # built in login and out views
    path("login/", authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path("logout/", authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path("profile/", user_views.profilepage, name='profile'),
    path('profile/<int:pk>/update_profile/', views.UpdateProfile.as_view(template_name='users/edit_profile.html'), name='update_profile'),
    path('create_profile/', views.CreateProfile.as_view(template_name='users/create_profile.html'), name='create_profile'),
    
]


# enables to use static files stored on the server

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings
from django.core.validators import MinLengthValidator

# Create your models here.
class item(models.Model):
    
    def __str__(self):
        return self.item_name
    
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default = 1)
    item_name = models.CharField(max_length = 200)
    item_disc = models.CharField(max_length = 200)
    item_price = models.IntegerField()
    #item_image = models.CharField(max_length = 800, default='https://images.pexels.com/photos/4439444/pexels-photo-4439444.jpeg?auto=compress&cs=tinysrgb&w=800')
    item_image =  models.ImageField(null =True, blank = True, upload_to='item_pictures')
    likes = models.ManyToManyField(User, related_name="item_likes")

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse("food:detail", kwargs = {"pk": self.pk}) 



class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    Item = models.ForeignKey(item, related_name="comments", on_delete=models.CASCADE)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'

mysite/food/forms.py
from django import forms
from .models import item ,Comment

class ItemForm(forms.ModelForm):
    class Meta():
        model = item
        fields = ['item_name','item_disc','item_price','item_image']

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ['text']

mysite/food/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from .models import item, Comment
from django.template import loader
from food.forms import ItemForm, CommentForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from food.owner import OwnerDeleteView, OwnerUpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.urls import reverse
# Create your views here.


def index(request):
    Item_list = item.objects.all()
    
    context = {
        'item_list' : Item_list,

    }
    return render(request,'food/index.html',context)


class index_class_view(ListView):
    model = item
    template_name = 'food/index.html'
    context_object_name = 'item_list'



def detail(request,item_id):
    Item = item.objects.get(pk=item_id)
    context = {
        'item':Item,
    }
    return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = item
    template_name = 'food/detail.html'

    def get_context_data(self,*args,**kwargs):
        food_menu = item.objects.all()
        context = super(FoodDetail, self).get_context_data()
        stuff = get_object_or_404(item, id= self.kwargs['pk'])
        total_likes = stuff.total_likes()
        liked = False
        if stuff.likes.filter(id = self.request.user.id).exists():
            liked = True
        context["total_likes"] = total_likes
        context["liked"] = liked
        return context


def create_item(request):
    Form = ItemForm(request.POST or None)

    if Form.is_valid():
        Form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':Form})

class CreateItem(CreateView):
    model = item
    fields = ['item_name','item_disc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        # find logged in user
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request,item_id):
    Item_update = item.objects.get(pk=item_id)
    Form_update = ItemForm(request.POST or None, instance = Item_update)

    if Form_update.is_valid():
        Form_update.save()
        return redirect('food:index')

    return  render(request,'food/item-form.html',{'form':Form_update, 'item':Item_update})

class UpdateItem(OwnerUpdateView):
    model = item
    fields = ['item_name','item_disc','item_price','item_image']
    template_name = 'food/update.html'

    def form_valid(self,form):
        # find logged in user
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def delete_item(request,item_id):
    Item_delete = item.objects.get(pk=item_id)
    
    if request.method == 'POST':
        Item_delete.delete()
        return redirect('food:index')

    return render(request, 'food/item-delete.html',{'item':Item_delete})


class ItemDeleteView(OwnerDeleteView):
    model = item
    template_name = 'food/item-delete.html'
    success_url = reverse_lazy('food:index')
    


class CommentCreateView(CreateView):
    model = Comment
    template_name = 'food/add_comment.html'
    fields = ['text']
    
    def post(self, request, pk) :
        
        f = get_object_or_404(item, id=pk)
        comment = Comment(text=request.POST['text'], user_name=request.user, Item=f)
        comment.save()
        return redirect(reverse('food:detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "food/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        Item = self.object.Item
        return reverse('food:detail', args=[Item.id])



def post_detail(request, slug):
    template_name = 'detail.html'
    Item = get_object_or_404(item, slug=slug)
    comments = Item.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'Item': Item,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})



def LikeView(request,pk):
    f = get_object_or_404(item, id=pk)
    liked = False
    if f.likes.filter(id = request.user.id).exists():
        f.likes.remove(request.user)
        liked = False
    else:
        f.likes.add(request.user)
        liked = True
    return redirect(reverse('food:detail', args=[pk]))



def SearchView(request):
    if request.method == 'POST':
        searched = request.POST.get('searched')
        searched_items = item.objects.filter(item_name__contains=searched)
        return render(request,'food/searched_item_list.html',{'searched':searched, 'searched_items':searched_items})
    else:
        return render(request,'food/searched_item_list.html',{})

mysite/food/templates/food/add_comment.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                
                <div class="card-header text-white bg-info">
                    
                    <div class="text-center">
                        <div class="card-title">
                            Add Comment
                        </div>
                    </div>
                    
                </div>
                
                
                <div class="card-body">

                    <form method="POST">
                    
                    {% csrf_token %}
                    
                    <div class="form-outline mb-4 text-center"> 
                       {{ form }}
                    </div>
                
                    <br>
                    
                    <div class="text-center">
                        <button class="btn btn-primary btn-block mb-4" type="submit">Add Comment</button>
                        <br>
                        <a href="{{ request.META.HTTP_REFERER }}"><input type="button" name="Cancel" value="Cancel"></a> 
                    </div>

                    </form>


                </div>
            
            </div>
        </div>
    </div>
</div>

{% endblock %}

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        
        <a class="navbar-brand" style="padding-left: 15px;" href="{% url 'food:index' %}" >FoodApp</a>
        

        <div class="navbar">
            <ul class="nav">

                <li class="nav-item">
                  {% if user.is_authenticated %}
                  <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
                  {% else %}
                  <a class="nav-link" href="#"></a>
                  {% endif %}
                </li>
                
                <li class="nav-item">
                  {% if user.is_authenticated %}
                    <a class="nav-link" href="#"></a>
                  {% else %}
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                  {% endif %}
                </li>

                <li class="nav-item">
                  {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                  {% else %}
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                  {% endif %}
                </li>
                
                {% if user.is_authenticated %}
                <li class="nav-item">
                  {% if user.profile.id %}
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                  {% else %}
                    <a class="nav-link" href="{% url 'create_profile' %}">Create Profile</a>
                  {% endif %}
                </li>
                {% endif %}
                
                
              </ul>

              <form class="d-flex" method="POST" action="{% url 'food:searched_item' %}">
                {% csrf_token %}
                <input class="form control me-2" type="search" placeholder="Search" aria-label="Search" name="searched">
                <button type="submit" class="btn btn-outline-primary">Search</button>
              </form>
              
             
        </div>


    </nav>

    {% if messages %}
    
       {% for message in messages %}
       
       <div class="alert alert-{{message.tags}}">{{message}}</div>
         
       {% endfor %}

    {% endif %}
    
    {% block body %}
    {% endblock %}

</body>
</html>

mysite/food/templates/food/comment_delete.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                
                <div class="card-header text-white bg-info">
                    
                    <div class="text-center">
                        <div class="card-title">
                            Delete Comment
                        </div>
                    </div>
                    
                </div>
                
                
                <div class="card-body">

                    <form method="POST">
    
                        {% csrf_token %}
                        <div class="text-center">
                            <h2> Are you sure you want to delete this comment?</h2>
                            <h5>{{comment.text}}</h5>
                            <button class="btn btn-primary btn-block mb-4" type="submit">Confirm</button>
                            <br>
                            <a href="{{ request.META.HTTP_REFERER }}"><input type="button" name="Cancel" value="Cancel"></a> 
                        </div>
                    </form>


                </div>
            
            </div>
        </div>
    </div>
</div>

{% endblock %}

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}

<div class="container">

    <div class="row">        
        
        <div class="col-md-6" style="padding-left: 150px;  padding-right: 0px;">
            {% if item.item_image %}
            <img src="{{ item.item_image.url }}"  height="350" width="350"/>
            {% else %}
            <img src="{% static 'users/images/coming_soon.jpg' %}"  height="350" width="350"/>
            {% endif %}
        </div>
        
        <div class="col-md-6">
           <h1>{{ object.item_name }}</h1> 
           <p>{{ object.item_disc }}</p>     
           <p>${{ object.item_price }} </p>
           <p>Posted by {{ object.user_name }} </p>

           <br>
           {% if user.is_authenticated %}
           <form action="{% url 'food:like_item' item.pk %}" method="POST">
                {% csrf_token %}
                
                {% if liked %}

                <button type="submit", name="item_id", value="{{ item.id }}", class="btn btn-danger btn-sm">Unlike</button>
                
                {% else %}
                <button type="submit", name="item_id", value="{{ item.id }}", class="btn btn-primary btn-sm">Like</button>
                {% endif %}
                - {{total_likes}} Likes
           </form>
           {% endif %}
           <br>


           {% if user == item.user_name %}
           <a href="{% url 'food:delete_item' item.id %}">Delete</a>
           
           <br>
           <a href="{% url 'food:update_item' item.id %}">Update</a>
           {% endif %}

            <br>
            <br>
            <br>

           <h2>Comments ...</h2>
           
           <br>

           {% if not item.comments.all %}
              
              <h1>No comments yet</h1> 
              
            {% else %}
               {% for comment in item.comments.all %}
              <strong>
                 {{ comment.user_name }} -
                 {{ comment.created_at}}
                 </strong>
                 {% if user == comment.user_name %}
                 <a href="{% url 'food:comment_delete' comment.id %}"><i class="bi bi-trash"></i>Delete</a>
                 {% endif %}
               <br>
                  {{ comment.text }}
                  
                  
                  
                  <br>
                {% endfor %}
            {% endif %}

            <br>
            <br>
            {% if user.is_authenticated %}
            <a href="{% url 'food:comment_create' item.pk %}">Add a comment </a>
            {% else %}
            <a href="{% url 'login' %}">Login to leave a comment </a>
            {% endif %}



        </div>

    </div>

</div>

{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
</head>
<body>

    {% block body %}

      {% for item in item_list %}
      
      <div class="container">

        <div class="row">        
            
            <div class="col-md-6" style="padding-left: 150px;  padding-right: 0px;">
                {% if item.item_image %}
                <img src="{{ item.item_image.url }}"  height="350" width="350"/>
                {% else %}
                <img src="{% static 'users/images/coming_soon.jpg' %}"  height="350" width="350"/>
                {% endif %}
            </div>
            
            <div class="col-md-4">
            <h1>{{ item.item_name }}</h1> 
            <p>{{ item.item_disc }}</p>     
            <p>${{ item.item_price }} </p>
            </div>

           

            <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

            </div>

        </div>
    </div>
<br>
       {% endfor %}

       
       

    {% endblock %}

</body>
</html>

mysite/food/templates/food/item-delete.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                
                <div class="card-header text-white bg-info">
                    
                    <div class="text-center">
                        <div class="card-title">
                            Delete Item
                        </div>
                    </div>
                    
                </div>
                
                
                <div class="card-body">

                    <form method="POST">
    
                        {% csrf_token %}
                        <div class="text-center">
                            <h2> Are you sure you want to delete {{item.item_name}}? </h2>
                            <button class="btn btn-primary btn-block mb-4" type="submit">Confirm</button>
                            <br>
                            <a href="{{ request.META.HTTP_REFERER }}"><input type="button" name="Cancel" value="Cancel"></a>
                        </div>
                    </form>


                </div>
            
            </div>
        </div>
    </div>
</div>

{% endblock %}

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                
                <div class="card-header text-white bg-info">
                    
                    <div class="text-center">
                        <div class="card-title">
                            Add Item
                        </div>
                    </div>
                    
                </div>
                
                
                <div class="card-body">

                    <form method="POST" enctype="multipart/form-data">
                    
                    {% csrf_token %}
                    
                    <div class="form-outline mb-4 text-center"> 
                       {{ form }}
                    </div>
                
                    <br>
                    
                    <div class="text-center">
                        <button class="btn btn-primary btn-block mb-4" type="submit">Add</button>
                        <br>
                        <a href="{% url 'food:index' %}">Cancel</a>
                    </div>

                    </form>


                </div>
            
            </div>
        </div>
    </div>
</div>

{% endblock %}

mysite/food/templates/food/searched_item_list.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">

    <div class="row">  

        <center>

           {% if searched %}

               <h1>You Searched For {{ searched }} </h1>
               
               <br>

               {% for food_item in searched_items %}

               <img src="{{ food_item.item_image.url }}" height="250" width="250" />
                - <strong>{{ food_item.item_name }}</strong>
                - <a href="{% url 'food:detail' food_item.id %}" class="btn btn-success">Detail Page</a>
                <br>
                <br>

               {% endfor %}

            {% else %}

                <h1>OOOps You Forgot To Search For An Item ...</h1>
            
            {% endif %}
        
        
        </center>

    </div>

</div>


{% endblock %}

mysite/food/templates/food/update.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                
                <div class="card-header text-white bg-info">
                    
                    <div class="text-center">
                        <div class="card-title">
                            Update Item
                        </div>
                    </div>
                    
                </div>
                
                
                <div class="card-body">

                    <form method="POST" enctype="multipart/form-data">
                    
                    {% csrf_token %}
                    
                    <div class="form-outline mb-4 text-center"> 
                       {{ form }}
                    </div>
                
                    <br>
                    
                    <div class="text-center">
                        <button class="btn btn-primary btn-block mb-4" type="submit">Update</button>
                        <br>
                        <a href="{{ request.META.HTTP_REFERER }}"><input type="button" name="Cancel" value="Cancel"></a>
                    </div>

                    </form>


                </div>
            
            </div>
        </div>
    </div>
</div>

{% endblock %}